### ISSUE TITLE
Update zync-database restore docs

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [3scale/3scale-Operations#7]
https://issues.redhat.com/browse/THREESCALE-4456

**Comment by slopezz** [comment]
Deprecated manual restore process of zync-database is already documented at https://github.com/3scale/3scale-Operations/blob/35e7a3851bc533500c6c8973c83b156f3c12fb3f/docs/backups.adoc#zync-database-2

However, as already documented https://github.com/3scale/3scale-Operations/blob/aea1cf08058004c7e95810ea350376c69a2ce750/docs/ha_dbs.adoc#3scale-ha-external-databases:
- It is recommended using external database, using for example a cloud database managed service which include automated backup/restore
- If using internal database, backup/restore should be done with the 3scale operator

Closing issue
